<testsuites>
  <!--Report is generated by Rally 0.8.0 at TIME-->
  <testsuite errors="0" failures="3" id="foo-bar-1" skipped="0" tests="9" time="1.111" timestamp="2001-01-01T00:00:00">
    <testcase classname="some.test.TestCase" name="test_foo" time="8" timestamp="2001-01-01T00:01:00" />
    <testcase classname="some.test.TestCase" name="test_skipped" time="0" timestamp="2001-01-01T00:02:00">
      <skipped>Skipped until Bug: 666 is resolved.</skipped>
    </testcase>
    <testcase classname="some.test.TestCase" name="test_xfail" time="3" timestamp="2001-01-01T00:03:00">
      <!--It is an expected failure due to: something-->
      <!--Traceback:
HEEELP-->
    </testcase>
    <testcase classname="some.test.TestCase" name="test_uxsuccess" time="3" timestamp="2001-01-01T00:04:00">
      <failure>It is an unexpected success due to: It should fail since I expect it</failure>
    </testcase>
  </testsuite>
  <testsuite errors="0" failures="33" id="foo-bar-2" skipped="0" tests="99" time="22.222" timestamp="2002-01-01T00:00:00">
    <testcase classname="some.test.TestCase" name="test_foo" time="8" timestamp="2001-02-01T00:01:00" />
    <testcase classname="some.test.TestCase" name="test_failed" time="8" timestamp="2001-02-01T00:02:00">
      <failure>HEEEEEEELP</failure>
    </testcase>
    <testcase classname="some.test.TestCase" name="test_skipped" time="0" timestamp="2001-02-01T00:03:00">
      <skipped>Skipped until Bug: 666 is resolved.</skipped>
    </testcase>
    <testcase classname="some.test.TestCase" name="test_xfail" time="4" timestamp="2001-02-01T00:04:00">
      <!--It is an expected failure due to: something-->
      <!--Traceback:
HEEELP-->
    </testcase>
  </testsuite>
  <testsuite errors="0" failures="33" id="foo-bar-3" skipped="0" tests="99" time="33.333" timestamp="2003-01-01T00:00:00">
    <testcase classname="some.test.TestCase" name="test_foo" time="8" timestamp="2001-03-01T00:01:00" />
    <testcase classname="some.test.TestCase" name="test_failed" time="7" timestamp="2001-03-01T00:02:00">
      <failure>HEEEEEEELP</failure>
    </testcase>
    <testcase classname="some.test.TestCase" name="test_skipped" time="0" timestamp="2001-03-01T00:03:00">
      <skipped>Skipped until Bug: 666 is resolved.</skipped>
    </testcase>
    <testcase classname="some.test.TestCase" name="test_xfail" time="3" timestamp="2001-03-01T00:04:00">
      <!--It is an expected failure due to: something-->
      <!--Traceback:
HEEELP-->
    </testcase>
  </testsuite>
</testsuites>
